DROP TABLE IF EXISTS INVENTORY ;

CREATE TABLE INVENTORY (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL,
  CATEGORY VARCHAR(250) NOT NULL,
  SUB_CATEGORY VARCHAR(250) NOT NULL,
  QUANTITY INT NOT NULL
);